"""update urls check model

Revision ID: 9a8863692fa9
Revises: 0c4cf9d9a034
Create Date: 2025-04-30 20:29:06.227680

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '9a8863692fa9'
down_revision: Union[str, None] = '0c4cf9d9a034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
