dynaconf_merge: true
default:
  DOMAIN: 'http://localhost:8000/'
  TIME_ZONE: "Europe/Moscow"
  SECRET_KEY: "5A82eF61Bd0C430a95CcfB8f5a0bC0D2"
  TEMPLATES_DIR: "../templates"

dev:
  DOMAIN: 'http://localhost:8000/'
  STATIC_DIR: "../static_files"

prod:
  DOMAIN: 'https://page-analyzer.pupsidian.ru/'
  STATIC_DIR: "../static"
