name: Build and Deploy Project

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/victorvangeli/python-project-83:latest
          provenance: false

  deploy:
    needs: build-and-push

    runs-on: self-hosted

    steps:
      - name: SSH to VPS and recreate container
        run: |
          docker compose -f /home/vvd/page-analyzer/docker-compose.yaml pull
          docker compose -f /home/vvd/page-analyzer/docker-compose.yaml up -d --build
